### ISSUE TITLE
WARNING: Multiple instances of Three.js being imported.

### ISSUE THREAD

**Issue by brianyuen** [DePasqualeOrg/three-immersive-controls#1]
Hi! First off, thanks for this. I was able to set up controls for VR in just a few minutes. One thing I did notice with my project, along with the demos listed in the README.md of this repo, was that I was getting this error in the console. 

`WARNING: Multiple instances of Three.js being imported.`

I'm running a fairly basic scene on macOS 12.4 with node v14.17.3 if it matters.
Thanks!

**Comment by DePasqualeOrg** [comment]
I see it happens in Chrome but not in Safari. It could have to do with the fact that I'm using my own patched version of Three.js on the examples due to this longstanding [bug](https://github.com/mrdoob/three.js/pull/22362) which interferes with some functionality in VR. Once it's fixed, I'll revert to the latest version and see if the error keeps happening.
